# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.p_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.p_lb.setMaximumSize(QtCore.QSize(16777215, 15))
        self.p_lb.setObjectName("p_lb")
        self.gridLayout.addWidget(self.p_lb, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_chb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.input_chb.setObjectName("input_chb")
        self.horizontalLayout.addWidget(self.input_chb)
        self.output_chb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.output_chb.setObjectName("output_chb")
        self.horizontalLayout.addWidget(self.output_chb)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.conn_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.conn_lb.setMaximumSize(QtCore.QSize(16777215, 15))
        self.conn_lb.setObjectName("conn_lb")
        self.gridLayout.addWidget(self.conn_lb, 2, 0, 1, 1)
        self.p_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p_le.setObjectName("p_le")
        self.gridLayout.addWidget(self.p_le, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.save_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.p_lb.setText(_translate("Dialog", "P ="))
        self.input_chb.setText(_translate("Dialog", "Стартовый"))
        self.output_chb.setText(_translate("Dialog", "Итоговый"))
        self.conn_lb.setText(_translate("Dialog", "Связи с элементами (номера через запятую)"))
        self.save_btn.setText(_translate("Dialog", "Сохранить"))
